teams_abbrev = {
    'ANA': 'Ducks',
    'ARI': 'Coyotes',
    'BOS': 'Bruins',
    'BUF': 'Sabres',
    'CGY': 'Flames',
    'CAR': 'Hurricanes',
    'CHI': 'Blackhawks',
    'COL': 'Avalanche',
    'CBJ': 'Blue Jackets',
    'DAL': 'Stars',
    'DET': 'Red Wings',
    'EDM': 'Oilers',
    'FLA': 'Panthers',
    'LAK': 'Kings',
    'MIN': 'Wild',
    'MTL': 'Canadiens',
    'NSH': 'Predators',
    'NJD': 'Devils',
    'NYI': 'Islanders',
    'NYR': 'Rangers',
    'OTT': 'Senators',
    'PHI': 'Flyers',
    'PIT': 'Penguins',
    'SJS': 'Sharks',
    'SEA': 'Kraken',
    'STL': 'Blues',
    'TBL': 'Lightning',
    'TOR': 'Maple Leafs',
    'VAN': 'Canucks',
    'VGK': 'Golden Knights',
    'WSH': 'Capitals',
    'WPG': 'Jets',
    'UTA': 'Hockey Club'
}