# Generated by Django 5.1.4 on 2024-12-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_dkdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkdata',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='dkdata',
            name='team_abbrev',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='blocked_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='position',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='team',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='toi',
            field=models.FloatField(help_text='Average time on ice per game in minutes', null=True),
        ),
    ]
