# Generated by Django 5.1.4 on 2024-12-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0004_dkdata_name_dkdata_team_abbrev_alter_apidata_assists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dkdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dkdata',
            name='team_abbrev',
        ),
        migrations.AddField(
            model_name='dkdata',
            name='player_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nhl.apidata'),
        ),
    ]
