# Generated by Django 5.1.4 on 2024-12-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0005_remove_dkdata_name_remove_dkdata_team_abbrev_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DkData',
            new_name='PlayerData',
        ),
    ]
