# Generated by Django 5.1.4 on 2024-12-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0006_rename_dkdata_playerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdata',
            name='player_data',
        ),
        migrations.AddField(
            model_name='playerdata',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='blocked_shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='position',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='shots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='team',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='toi',
            field=models.FloatField(help_text='Average time on ice per game in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
